"""Base strategy interface and signal dataclass."""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any

import pandas as pd

from app.core.enums import SignalType


@dataclass
class StrategySignal:
    """Signal generated by a strategy.

    Strategies produce signals; they never place orders directly.
    """

    signal_type: SignalType
    symbol: str
    price: float
    strength: float = 1.0  # 0.0 to 1.0
    stop_loss: float | None = None
    take_profit: float | None = None
    timestamp: datetime | None = None
    metadata: dict[str, Any] = field(default_factory=dict)


class BaseStrategy(ABC):
    """Abstract base strategy interface.

    Every strategy must inherit from this class and implement `generate_signals`.
    Strategies may only generate signals — they may not place orders directly.
    """

    name: str = "base"
    description: str = ""
    version: str = "1.0.0"

    def __init__(self, params: dict[str, Any] | None = None) -> None:
        """Initialize the strategy with configurable parameters.

        Args:
            params: Strategy-specific parameters. Subclasses define their defaults.
        """
        self.params: dict[str, Any] = {**self.default_params()}
        if params:
            self.params.update(params)

    @abstractmethod
    def default_params(self) -> dict[str, Any]:
        """Return default parameter values for this strategy."""
        ...

    @abstractmethod
    def generate_signals(self, candles: pd.DataFrame) -> list[StrategySignal]:
        """Generate trading signals from candle data.

        Args:
            candles: DataFrame with columns [open, high, low, close, volume].
                     Index should be DatetimeIndex or have an 'open_time' column.

        Returns:
            List of StrategySignal objects. Typically one signal per call
            (the latest candle's signal), but may return multiple for
            backtesting across the full DataFrame.
        """
        ...

    def validate_candles(self, candles: pd.DataFrame) -> bool:
        """Validate that the DataFrame has required columns and sufficient data."""
        required_cols = {"open", "high", "low", "close", "volume"}
        if not required_cols.issubset(candles.columns):
            return False
        min_periods = self.params.get("min_periods", 50)
        return len(candles) >= min_periods

    def __repr__(self) -> str:
        return f"{self.__class__.__name__}(name={self.name!r}, params={self.params})"
